<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "product_catalog"
 *
 * Auto generated by Extension Builder 2014-11-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Catalog',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Martin Gjoshevski',
	'author_email' => 'martin.gjoshevski@tend.si',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);